#!/usr/bin/env bash
# Record the prove-fullstack P2 journey: a briefed issue is fanned out to the
# squad from the TUI (Squads `x`), then the Pipeline board is watched while the
# role-gated stages pull it Triage -> Implement -> Review -> QA -> Done with real
# agents, ending on the Done column count incrementing.
#
# Prereqs (see docs/hangar/prove-fullstack-goal.md): the iso instance is up, the
# squad + roles exist, `pipeline init` ran, and the issue to fan out is the LAST
# issue in the workspace (the tape walks `j` to the bottom of the issue list).
# Authoring a briefed issue without dispatching it has no TUI path yet (REPORT.md
# gap 17), so the caller creates it with `ainb hangar issue create` first.
#
# Usage: ISO=... WT=... ISSUE_ROWS=<count of issues in the workspace> bash scripts/hangar/record-fullstack-p2.sh
# Output: docs/hangar/proofs/fullstack/p2-pipeline.{gif,mp4} + p2-N-*.png
set -euo pipefail

ISO="${ISO:-/home/claude/ainb-e2e-home}"
WT="${WT:-$(cd "$(dirname "$0")/../.." && pwd)}"
BIN="$WT/target/debug/ainb"
DAEMON="$WT/target/debug/ainb-hangar-daemon"
PLUGINS="$WT/dist/plugins"
OUT="$WT/docs/hangar/proofs/fullstack"
DB="$ISO/.agents-in-a-box/hangar.db"
LAUNCH="HOME='$ISO' TMUX_TMPDIR='$ISO/tmux' AINB_PLUGIN_ROOT='$PLUGINS' AINB_BIN='$BIN' AINB_HANGAR_DAEMON_BIN='$DAEMON' exec env -u AINB_HANGAR_HOME -u AINB_HOME -u TMUX -u TMUX_PANE '$BIN' tui"

for t in vhs ffmpeg sqlite3; do command -v "$t" >/dev/null || { echo "missing: $t" >&2; exit 2; }; done
[ -x "$BIN" ] || { echo "no ainb binary at $BIN" >&2; exit 2; }
[ -S "$ISO/.agents-in-a-box/hangar.sock" ] || { echo "iso daemon not running" >&2; exit 2; }
mkdir -p "$OUT"

ISSUE_ROWS="${ISSUE_ROWS:-$(sqlite3 "$DB" "select count(*) from issue;")}"
DOWN=$((ISSUE_ROWS - 1))
DONE_BEFORE=$(sqlite3 "$DB" "select count(*) from board_card bc join board_column c on c.id=bc.column_id where c.name='Done';")
DONE_AFTER=$((DONE_BEFORE + 1))

TAPE="$OUT/p2-pipeline.tape"
{
  cat <<EOF
# Generated by scripts/hangar/record-fullstack-p2.sh. Baked paths are this host's.
Output p2-pipeline.gif
Output p2-pipeline.mp4
Set Shell "bash"
Set FontSize 13
Set Width 2000
Set Height 960
Set Padding 12
Set TypingSpeed 40ms

Hide
Type "$LAUNCH"
Enter
Wait+Screen@60s /navigate/
Show
Type "g"
Wait+Screen@30s /Settings/
Sleep 1s
Type "1"
Sleep 1s
EOF
  for _ in $(seq 1 "$DOWN"); do printf 'Type "j"\nSleep 400ms\n'; done
  cat <<EOF
Enter
Sleep 2s
Screenshot p2-1-issue-detail.png
Escape
Sleep 1s
Type "S"
Sleep 2s
Screenshot p2-2-squad-roster.png
Type "x"
Sleep 3s
Screenshot p2-3-fanout-ack.png
Type "B"
Sleep 3s
Screenshot p2-4-board-triage.png
Sleep 60s
Screenshot p2-5-board-implement.png
Sleep 120s
Screenshot p2-6-board-mid.png
Wait+Screen@1200s /Done \(${DONE_AFTER}\)/
Sleep 2s
Screenshot p2-7-board-done.png
Type "1"
Sleep 2s
Screenshot p2-8-issue-done.png
Type "U"
Sleep 3s
Screenshot p2-9-usage.png
Type "q"
Sleep 1s
EOF
} > "$TAPE"

cd "$OUT"
rm -f p2-pipeline.gif p2-pipeline.mp4 p2-[0-9]-*.png
VHS_NO_SANDBOX=true vhs "$TAPE"

if [ ! -s p2-pipeline.gif ] && [ -s p2-pipeline.mp4 ]; then
  echo "gif empty; regenerating from mp4" >&2
  ffmpeg -y -loglevel error -i p2-pipeline.mp4 \
    -vf "fps=4,scale=1400:-1:flags=lanczos,split[s0][s1];[s0]palettegen=max_colors=128[p];[s1][p]paletteuse=dither=bayer" \
    p2-pipeline.gif
  command -v gifsicle >/dev/null && gifsicle -O3 --lossy=60 -o p2-pipeline.gif p2-pipeline.gif
fi

for f in p2-pipeline.gif p2-pipeline.mp4 p2-1-issue-detail.png p2-7-board-done.png; do
  [ -s "$f" ] || { echo "artifact missing or empty: $f" >&2; exit 1; }
done
ls -la p2-pipeline.gif p2-pipeline.mp4 p2-[0-9]-*.png
