#!/usr/bin/env bash
# Record the prove-fullstack P1 journey (create issue via the TUI wizard, real
# agent runs, card lands in done) against an ALREADY RUNNING isolated instance.
#
# Prereqs (see docs/hangar/prove-fullstack-goal.md Phase 0): the iso home is
# provisioned, its daemon is up, the repo roster offers the app repo, and an
# agent named impl-1 exists. This script only drives + records; it never
# provisions, never touches the primary instance, and never kills anything but
# nothing at all (the TUI exits on its own `q`).
#
# Usage: ISO=/home/claude/ainb-e2e-home WT=<worktree> bash scripts/hangar/record-fullstack-p1.sh [title-suffix]
# Output: docs/hangar/proofs/fullstack/p1-happy-path.{gif,mp4} + p1-N-*.png
set -euo pipefail

ISO="${ISO:-/home/claude/ainb-e2e-home}"
WT="${WT:-$(cd "$(dirname "$0")/../.." && pwd)}"
BIN="$WT/target/debug/ainb"
DAEMON="$WT/target/debug/ainb-hangar-daemon"
PLUGINS="$WT/dist/plugins"
OUT="$WT/docs/hangar/proofs/fullstack"
SUFFIX="${1:-}"
# vhs 0.11 has no `Set Env`; the launch line carries the whole env contract.
LAUNCH="HOME='$ISO' TMUX_TMPDIR='$ISO/tmux' AINB_PLUGIN_ROOT='$PLUGINS' AINB_BIN='$BIN' AINB_HANGAR_DAEMON_BIN='$DAEMON' exec env -u AINB_HANGAR_HOME -u AINB_HOME -u TMUX -u TMUX_PANE '$BIN' tui"

for t in vhs ffmpeg; do command -v "$t" >/dev/null || { echo "missing: $t" >&2; exit 2; }; done
[ -x "$BIN" ] || { echo "no ainb binary at $BIN" >&2; exit 2; }
[ -S "$ISO/.agents-in-a-box/hangar.sock" ] || { echo "iso daemon not running" >&2; exit 2; }
mkdir -p "$OUT"

# Kanban done-count before the run: the tape terminates when it increments.
DB="$ISO/.agents-in-a-box/hangar.db"
DONE_BEFORE=$(sqlite3 "$DB" "select count(*) from agent_task_queue where status='done';")
DONE_AFTER=$((DONE_BEFORE + 1))

TAPE="$OUT/p1-happy-path.tape"
# Typed text avoids capital H and W: the host steals those keys from plugin
# text inputs (defect 3 in REPORT.md) until that fix lands.
cat > "$TAPE" <<EOF
# Generated by scripts/hangar/record-fullstack-p1.sh. Baked paths are this host's.
Output p1-happy-path.gif
Output p1-happy-path.mp4
Set Shell "bash"
Set FontSize 13
Set Width 1800
Set Height 960
Set Padding 12
Set TypingSpeed 40ms

Hide
Type "$LAUNCH"
Enter
Wait+Screen@60s /navigate/
Show
Type "g"
Wait+Screen@30s /Settings/
Sleep 1s
Screenshot p1-1-hangar-issues.png

Type "1"
Sleep 1s
Type "c"
Wait+Screen@10s /New task/
Sleep 1s
Type "Add GET /api/version endpoint${SUFFIX}"
Tab
Type "Add a GET /api/version route to the hono api under api/ returning {version} read from api/package.json, plus a vitest test for it. Run npm test and npm run check yourself and keep them green."
Enter
Type "Finish by committing conventionally (plain commits, no signing), pushing the current branch, and opening a pull request: gh pr create --fill --base main."
Tab
Tab
Tab
Tab
Tab
Tab
Tab
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Tab
Tab
Tab
Sleep 1s
Right
Sleep 2s
Screenshot p1-2-wizard-filled.png
Enter
Sleep 3s
Screenshot p1-3-dispatched.png

Type "K"
Wait+Screen@60s /running \(1\)/
Sleep 2s
Screenshot p1-4-kanban-running.png
Wait+Screen@900s /done \(${DONE_AFTER}\)/
Sleep 2s
Screenshot p1-5-kanban-done.png

Type "U"
Sleep 3s
Screenshot p1-6-usage.png
Type "q"
Sleep 1s
EOF

cd "$OUT"
rm -f p1-happy-path.gif p1-happy-path.mp4 p1-[0-9]-*.png
VHS_NO_SANDBOX=true vhs "$TAPE"

# vhs's gif encoder has been seen to hang and leave a zero-byte gif beside a
# good mp4; rebuild the gif from the mp4 with a palette pass when that happens.
if [ ! -s p1-happy-path.gif ] && [ -s p1-happy-path.mp4 ]; then
  echo "gif empty; regenerating from mp4" >&2
  ffmpeg -y -loglevel error -i p1-happy-path.mp4 \
    -vf "fps=6,scale=1400:-1:flags=lanczos,split[s0][s1];[s0]palettegen=max_colors=128[p];[s1][p]paletteuse=dither=bayer" \
    p1-happy-path.gif
  command -v gifsicle >/dev/null && gifsicle -O3 --lossy=60 -o p1-happy-path.gif p1-happy-path.gif
fi

# Never trust vhs silently: every artifact must exist and be non-empty.
for f in p1-happy-path.gif p1-happy-path.mp4 p1-1-hangar-issues.png p1-5-kanban-done.png; do
  [ -s "$f" ] || { echo "artifact missing or empty: $f" >&2; exit 1; }
done
ls -la p1-happy-path.gif p1-happy-path.mp4 p1-[0-9]-*.png
