#!/usr/bin/env bash
# Record the prove-fullstack P3 journey: a board card is launched in
# INTERACTIVE mode, the real claude session raises an AskUserQuestion, the ASK
# lands on Control Center, the operator answers option 2 by digit, the board
# flips to "0 need you", and (after quitting the TUI, in the same terminal) the
# session's own transcript proves which option the agent received.
#
# Prereqs: iso instance up with lifecycle hooks installed in its .claude home,
# a board whose FIRST board carries a card whose TITLE instructs the agent to
# ask a two-option AskUserQuestion (see REPORT.md, card #MNT1RV), and that card
# is the focused card when Boards opens.
#
# Usage: ISO=... WT=... bash scripts/hangar/record-fullstack-p3.sh
# Output: docs/hangar/proofs/fullstack/p3-human-loop.{gif,mp4} + p3-N-*.png
set -euo pipefail

ISO="${ISO:-/home/claude/ainb-e2e-home}"
WT="${WT:-$(cd "$(dirname "$0")/../.." && pwd)}"
BIN="$WT/target/debug/ainb"
DAEMON="$WT/target/debug/ainb-hangar-daemon"
PLUGINS="$WT/dist/plugins"
OUT="$WT/docs/hangar/proofs/fullstack"
# No `exec` here: the shell must survive `q` so the proof commands can run after.
LAUNCH="HOME='$ISO' TMUX_TMPDIR='$ISO/tmux' AINB_PLUGIN_ROOT='$PLUGINS' AINB_BIN='$BIN' AINB_HANGAR_DAEMON_BIN='$DAEMON' env -u AINB_HANGAR_HOME -u AINB_HOME -u TMUX -u TMUX_PANE '$BIN' tui"
# Printed after the TUI quits: the newest transcript's tool_result line names the
# option the agent actually received. Lives in a helper script so the tape's
# Type line carries no quotes and no option text (which could match its echo).
PROOF="$ISO/p3-proof.sh"
cat > "$PROOF" <<'PROOF_EOF'
#!/usr/bin/env bash
P=$(ls -t "$HOME"/.claude/projects/*/*.jsonl | head -1)
echo "TRANSCRIPT $(basename "$P")"
grep -o 'have been answered: .\{0,70\}' "$P" | head -1
PROOF_EOF
chmod +x "$PROOF"

for t in vhs ffmpeg sqlite3; do command -v "$t" >/dev/null || { echo "missing: $t" >&2; exit 2; }; done
[ -x "$BIN" ] || { echo "no ainb binary at $BIN" >&2; exit 2; }
[ -S "$ISO/.agents-in-a-box/hangar.sock" ] || { echo "iso daemon not running" >&2; exit 2; }
mkdir -p "$OUT"

TAPE="$OUT/p3-human-loop.tape"
cat > "$TAPE" <<EOF
# Generated by scripts/hangar/record-fullstack-p3.sh. Baked paths are this host's.
Output p3-human-loop.gif
Output p3-human-loop.mp4
Set Shell "bash"
Set FontSize 13
Set Width 1800
Set Height 960
Set Padding 12
Set TypingSpeed 40ms

Hide
Type "$LAUNCH"
Enter
Wait+Screen@60s /navigate/
Show
Type "g"
Wait+Screen@30s /Settings/
Sleep 1s
Type "B"
Sleep 2s
Screenshot p3-1-board-card.png
Enter
Sleep 1s
Down
Sleep 1s
Screenshot p3-2-run-interactive.png
Enter
Sleep 3s
Screenshot p3-3-launched.png
Type "C"
Sleep 2s
Screenshot p3-4-control-center-waiting.png
Wait+Screen@300s /1 need you/
Sleep 2s
Screenshot p3-5-ask-raised.png
Type "2"
Sleep 5s
Screenshot p3-6-answered-flip.png
Type "q"
Sleep 2s
Screenshot p3-7-back-home.png
Type "q"
Sleep 3s
Sleep 1s
Type "HOME='$ISO' bash $PROOF"
Enter
Wait+Screen@30s /TRANSCRIPT/
Sleep 3s
Screenshot p3-8-transcript-proof.png
EOF

cd "$OUT"
rm -f p3-human-loop.gif p3-human-loop.mp4 p3-[0-9]-*.png
VHS_NO_SANDBOX=true vhs "$TAPE"

if [ ! -s p3-human-loop.gif ] && [ -s p3-human-loop.mp4 ]; then
  echo "gif empty; regenerating from mp4" >&2
  ffmpeg -y -loglevel error -i p3-human-loop.mp4 \
    -vf "fps=6,scale=1400:-1:flags=lanczos,split[s0][s1];[s0]palettegen=max_colors=128[p];[s1][p]paletteuse=dither=bayer" \
    p3-human-loop.gif
  command -v gifsicle >/dev/null && gifsicle -O3 --lossy=60 -o p3-human-loop.gif p3-human-loop.gif
fi

for f in p3-human-loop.gif p3-human-loop.mp4 p3-5-ask-raised.png p3-6-answered-flip.png p3-8-transcript-proof.png; do
  [ -s "$f" ] || { echo "artifact missing or empty: $f" >&2; exit 1; }
done
ls -la p3-human-loop.gif p3-human-loop.mp4 p3-[0-9]-*.png
