#!/usr/bin/env bash
# Record the prove-fullstack P4 walk: the help overlay, every observability
# screen after real runs (Kanban, Usage, Daemon health, Logs with the error
# filter, Inbox, Fleet), then three levers with visible effect: the Settings
# notification grid toggle (round-tripped and restored), the Boards depends-on
# picker, and a run of a blocked card refused with the daemon's reason.
#
# Prereqs: iso instance up after the P1-P3 legs (so the screens carry real
# data), and the sandbox board's THIRD card blocked by its second (see REPORT.md).
#
# Usage: ISO=... WT=... bash scripts/hangar/record-fullstack-p4.sh
# Output: docs/hangar/proofs/fullstack/p4-levers.{gif,mp4} + p4-N-*.png
set -euo pipefail

ISO="${ISO:-/home/claude/ainb-e2e-home}"
WT="${WT:-$(cd "$(dirname "$0")/../.." && pwd)}"
BIN="$WT/target/debug/ainb"
DAEMON="$WT/target/debug/ainb-hangar-daemon"
PLUGINS="$WT/dist/plugins"
OUT="$WT/docs/hangar/proofs/fullstack"
LAUNCH="HOME='$ISO' TMUX_TMPDIR='$ISO/tmux' AINB_PLUGIN_ROOT='$PLUGINS' AINB_BIN='$BIN' AINB_HANGAR_DAEMON_BIN='$DAEMON' exec env -u AINB_HANGAR_HOME -u AINB_HOME -u TMUX -u TMUX_PANE '$BIN' tui"

for t in vhs ffmpeg; do command -v "$t" >/dev/null || { echo "missing: $t" >&2; exit 2; }; done
[ -x "$BIN" ] || { echo "no ainb binary at $BIN" >&2; exit 2; }
[ -S "$ISO/.agents-in-a-box/hangar.sock" ] || { echo "iso daemon not running" >&2; exit 2; }
mkdir -p "$OUT"

TAPE="$OUT/p4-levers.tape"
cat > "$TAPE" <<EOF
# Generated by scripts/hangar/record-fullstack-p4.sh. Baked paths are this host's.
Output p4-levers.gif
Output p4-levers.mp4
Set Shell "bash"
Set FontSize 13
Set Width 1800
Set Height 960
Set Padding 12
Set TypingSpeed 40ms

Hide
Type "$LAUNCH"
Enter
Wait+Screen@60s /navigate/
Show
Type "g"
Wait+Screen@30s /Settings/
Sleep 1s
Type "?"
Sleep 2s
Screenshot p4-1-help.png
Escape
Sleep 1s
Type "K"
Sleep 2s
Screenshot p4-2-kanban.png
Type "U"
Sleep 2s
Screenshot p4-3-usage.png
Type "D"
Sleep 2s
Screenshot p4-4-daemon.png
Type "L"
Sleep 2s
Type "e"
Sleep 2s
Screenshot p4-5-logs-errors.png
Type "I"
Sleep 2s
Screenshot p4-6-inbox.png
Type "F"
Sleep 2s
Type "5"
Sleep 2s
Screenshot p4-7-fleet.png
Type ","
Sleep 2s
Type "j"
Sleep 400ms
Type "j"
Sleep 400ms
Type "j"
Sleep 400ms
Type "j"
Sleep 400ms
Type "j"
Sleep 1s
Screenshot p4-8-notify-grid.png
Space
Sleep 2s
Screenshot p4-9-notify-toggled.png
Space
Sleep 2s
Type "B"
Sleep 2s
Down
Sleep 800ms
Down
Sleep 1s
Screenshot p4-10-blocked-card.png
Type "w"
Sleep 2s
Screenshot p4-11-depends-on-picker.png
Escape
Sleep 1s
Enter
Sleep 1s
Enter
Wait+Screen@20s /blocked by unfinished cards/
Sleep 2s
Screenshot p4-12-run-refused.png
Type "q"
Sleep 1s
Type "q"
Sleep 1s
EOF

cd "$OUT"
rm -f p4-levers.gif p4-levers.mp4 p4-[0-9]*-*.png
VHS_NO_SANDBOX=true vhs "$TAPE"

if [ ! -s p4-levers.gif ] && [ -s p4-levers.mp4 ]; then
  echo "gif empty; regenerating from mp4" >&2
  ffmpeg -y -loglevel error -i p4-levers.mp4 \
    -vf "fps=6,scale=1400:-1:flags=lanczos,split[s0][s1];[s0]palettegen=max_colors=128[p];[s1][p]paletteuse=dither=bayer" \
    p4-levers.gif
  command -v gifsicle >/dev/null && gifsicle -O3 --lossy=60 -o p4-levers.gif p4-levers.gif
fi

for f in p4-levers.gif p4-levers.mp4 p4-1-help.png p4-9-notify-toggled.png p4-12-run-refused.png; do
  [ -s "$f" ] || { echo "artifact missing or empty: $f" >&2; exit 1; }
done
ls -la p4-levers.gif p4-levers.mp4 p4-[0-9]*-*.png
