//! `ainb keymap list` output and generated shortcut documentation.

use anyhow::Result;
use clap::Subcommand;
use serde::Serialize;

use crate::app::keymap::{Chord, KeyAction, Keymap};
use crate::app::keymap_toml::KeymapOverrides;
use crate::cli::OutputFormat;

/// Keymap command group.
#[derive(Debug, Subcommand)]
pub enum KeymapCommands {
    /// Print the merged, effective keymap.
    List,
}

/// Output representation for keymap rows.
#[derive(Debug, Clone, Copy)]
pub enum KeymapFormat {
    Md,
    Json,
}

#[derive(Serialize)]
struct JsonRow<'a> {
    context: String,
    chord: Option<&'a str>,
    event: &'a str,
    action: &'static str,
    description: &'a str,
}

/// Execute the keymap CLI.
pub fn execute(command: KeymapCommands, format: OutputFormat) -> Result<()> {
    match command {
        KeymapCommands::List => print_list(match format {
            OutputFormat::Json => KeymapFormat::Json,
            OutputFormat::Text | OutputFormat::Markdown => KeymapFormat::Md,
            OutputFormat::Csv => {
                anyhow::bail!("ainb keymap list supports only --format md or json")
            }
        }),
    }
}

fn merged_keymap() -> Keymap {
    let defaults = Keymap::defaults();
    let Some(path) = KeymapOverrides::default_path() else {
        return defaults;
    };
    match KeymapOverrides::from_path(&path).and_then(|overrides| {
        defaults.clone().with_overrides(&overrides).map_err(|error| error.to_string())
    }) {
        Ok(keymap) => keymap,
        Err(error) => {
            tracing::warn!(path = %path.display(), error = %error, "ignoring invalid keymap override");
            defaults
        }
    }
}

fn print_list(format: KeymapFormat) -> Result<()> {
    let keymap = merged_keymap();
    match format {
        KeymapFormat::Md => print_markdown(&keymap),
        KeymapFormat::Json => print_json(&keymap),
    }
}

fn print_markdown(keymap: &Keymap) -> Result<()> {
    // Starlight frontmatter, not decoration: the site's `docs` collection
    // loads `docs/**` through `docsSchema()`, which rejects any page without a
    // `title`. The generated page replaced a hand-written one that carried the
    // block, so emitting it here is what keeps `Build site` green. The `title`
    // renders as the page's h1, so no `# Keyboard shortcuts` heading follows.
    println!("---");
    println!("title: \"Keyboard shortcuts\"");
    println!(
        "description: \"Every key the TUI dispatches, by context, generated from the built-in keymap table.\""
    );
    println!("---\n");
    println!("Generated by `ainb keymap list --format md`. Do not edit by hand.\n");
    let mut last_context = None;
    // A shortcuts page lists keys. Unbound rows (the pointer commands) have
    // none, and `ainb keymap list --format json` still lists them.
    for binding in keymap.bindings().filter(|binding| binding.chord.is_some()) {
        let context = binding.ctx.name();
        if last_context.as_ref() != Some(&context) {
            if last_context.is_some() {
                println!();
            }
            println!("## {}\n", context.replace('_', " "));
            println!("| Key | Action | Description |");
            println!("| --- | --- | --- |");
            last_context = Some(context);
        }
        println!(
            "| `{}` | `{}` | {} |",
            binding.chord.as_ref().map_or("unbound", Chord::as_str),
            binding.id,
            binding.doc
        );
    }
    Ok(())
}

fn print_json(keymap: &Keymap) -> Result<()> {
    let rows = keymap
        .bindings()
        .map(|binding| JsonRow {
            context: binding.ctx.name(),
            chord: binding.chord.as_ref().map(Chord::as_str),
            event: binding.id,
            action: action_name(&binding.action),
            description: binding.doc,
        })
        .collect::<Vec<_>>();
    println!("{}", serde_json::to_string_pretty(&rows)?);
    Ok(())
}

const fn action_name(action: &KeyAction) -> &'static str {
    match action {
        KeyAction::App(_) => "app",
        KeyAction::Ui(_) => "ui",
        KeyAction::Passthrough => "passthrough",
        KeyAction::OpenSlashPalette => "open_slash_palette",
        KeyAction::Text(_) => "text",
    }
}
