// Generated by `cargo test -p ainb-desktop --features typescript-bindings --test bindings`
// from the Rust types the webview sends and receives. Do not edit.
// This file has been generated by Specta. Do not edit this file manually.
/**
 *  A catalog dependency as the page lists it: detected, never installed by
 *  the page itself.
 */
export type DependencyView = {
	id: string,
	name: string,
	why: string,
	required: boolean,
	satisfied: boolean,
	/**
	 *  Whether the catalog knows how to install it here; otherwise `hint`
	 *  says what to run by hand.
	 */
	auto_installable: boolean,
	hint: string,
};

/**  Where the OpenTelemetry setup stands, from `ainb_app::otel::status`. */
export type OtelView = {
	env_file_present: boolean,
	settings_env_present: boolean,
	alloy_installed: boolean,
	alloy_running: boolean,
};

/**  One row the palette offers: a command the webview may send by name. */
export type PaletteEntry = {
	id: string,
	/**  What the row does, as the keymap documents it. */
	doc: string,
	/**  The context the row belongs to, for the palette to group by. */
	context: string,
	/**  The key that runs it, when it has one. */
	chord: string | null,
	/**
	 *  Whether the reducer would run it in the state as it stands. A row that
	 *  is not active is still offered, greyed, rather than vanishing as the
	 *  user moves around.
	 */
	active: boolean,
};

/**
 *  The intents a DOM renderer sends: a key, a named command, pasted text.
 * 
 *  A subset of [`Intent`] with the same wire spelling. There is no `Mouse`:
 *  the webview hit-tests its own DOM and sends the command a press means, so a
 *  terminal cell position has nothing to hit here.
 */
export type RendererIntent = ({ Key: string }) & { Command?: never; Text?: never } | ({ Command: [string, unknown] }) & { Key?: never; Text?: never } | ({ Text: string }) & { Command?: never; Key?: never };

/**
 *  What the settings page's Setup panel shows: a host read at the moment it
 *  was asked for, never a framed section.
 */
export type SetupView = {
	dependencies: DependencyView[],
	tmux_conf_present: boolean,
	otel: OtelView,
};

/**
 *  One of the writes the settings page may ask the shell to confirm.
 * 
 *  `Debug` is written by hand: the telemetry write carries a token, and a
 *  `{:?}` of it would put that token in the log `show_log` reads back into
 *  the window.
 */
export type SetupWrite = 
/**  Install the catalog dependency `id`, the way onboarding's `i` does. */
{ kind: "install_dependency"; id: string } | 
/**
 *  Install every unmet dependency the catalog can install itself, the way
 *  onboarding's `I` does one at a time.
 */
{ kind: "install_all_dependencies" } | 
/**
 *  Write ainb's tmux configuration to `~/.tmux.conf`, keeping a backup of
 *  what was there, the way onboarding's `t` does.
 */
{ kind: "write_tmux_config" } | 
/**
 *  Finish the OpenTelemetry setup onboarding's Next or Finish runs with
 *  the three fields filled: the env file under ainb, then Claude Code's
 *  settings and the shell rc outside it, and the collector if installed.
 */
{ kind: "finish_open_telemetry"; otlp_endpoint: string; instance_id: string; api_token: string };
