// ABOUTME: AppState.ts is the TypeScript contract for mirror frames. It is
// generated from the Rust types and committed; this test regenerates it and
// fails on any difference, and CI runs it with the feature on.

#![cfg(feature = "typescript-bindings")]

#[path = "support/home.rs"]
mod home;

use home::ScopedHome;

use ainb_app::wire::bindings::{APP_STATE_TS, typescript};

#[test]
fn app_state_ts_matches_the_rust_types() {
    let rendered = typescript().unwrap_or_else(|error| panic!("{error}"));
    if std::env::var_os("UPDATE_APP_STATE_TS").is_some() {
        std::fs::write(APP_STATE_TS, &rendered).expect("write AppState.ts");
        return;
    }
    let committed = std::fs::read_to_string(APP_STATE_TS).unwrap_or_default();
    assert!(
        committed == rendered,
        "ainb-app/bindings/AppState.ts is stale. Regenerate with\n  \
         UPDATE_APP_STATE_TS=1 cargo test -p ainb-app --features typescript-bindings --test bindings\n\
         and commit it."
    );
}

/// The sample frames as TypeScript literals typed by `AppState.ts`. `tsc
/// --strict` over this file fails on any field a frame carries that the
/// contract does not declare, any declared field a frame lacks, and any value
/// of the wrong kind: the check that the generated types describe the JSON a
/// host actually sends, not merely compile. CI writes it and runs `tsc`.
#[test]
fn sample_frames_as_typed_typescript() {
    use ainb_app::SectionId;
    use ainb_app::wire::frame::HostId;
    use ainb_app::wire::{section_json, section_name, shape};

    let Some(out) = std::env::var_os("WRITE_BINDINGS_SAMPLE") else {
        return;
    };
    let _home = ScopedHome::new();
    let mut ts = String::from(
        "// Generated by tests/bindings.rs for `tsc --noEmit --strict`. Not committed.\n\
         import type { SectionBodies } from \"./AppState\";\n\n",
    );
    for (index, state) in shape::sample_states(&mut shape::PlainSeed).iter().enumerate() {
        let bodies: serde_json::Map<String, serde_json::Value> = SectionId::ALL
            .into_iter()
            .map(|id| {
                (
                    section_name(id).to_string(),
                    section_json(state, id, &HostId::local()),
                )
            })
            .collect();
        ts.push_str(&format!(
            "export const sample{index}: SectionBodies = {};\n\n",
            serde_json::to_string_pretty(&bodies).expect("sample bodies serialise")
        ));
    }
    std::fs::write(out, ts).expect("write sample frames");
}
