//! TypeScript for the two shapes that cross this shell's IPC seam, rendered
//! from the Rust types by specta behind the `typescript-bindings` feature and
//! committed as `bindings/Desktop.ts`.
//!
//! The frame types have had this since D15 (`ainb_app::wire::bindings`); these
//! two were hand-written TypeScript in the window, so renaming a variant or a
//! field in Rust left the window compiling and wrong (#1158).
//!
//! Every field whose Rust type belongs to `ainb-app` carries an explicit
//! `specta(type)`: a chord and a command id are strings on the wire by their
//! own serde attributes, and an argument payload is arbitrary JSON. Naming them
//! here keeps this crate's bindings independent of whether `ainb-app` was built
//! with its own bindings feature.

use specta::Types;

/// Where the committed file lives, relative to the `ainb-desktop` crate.
pub const DESKTOP_TS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/bindings/Desktop.ts");

/// The rendered `Desktop.ts`.
///
/// # Errors
///
/// When a type cannot be expressed in TypeScript.
pub fn typescript() -> Result<String, specta_typescript::Error> {
    let types = Types::default()
        .register::<crate::intent::RendererIntent>()
        .register::<crate::host::PaletteEntry>()
        .register::<crate::setup::SetupWrite>()
        .register::<crate::setup::SetupView>();
    specta_typescript::Typescript::default()
        .header(
            "// Generated by `cargo test -p ainb-desktop --features typescript-bindings --test bindings`\n\
             // from the Rust types the webview sends and receives. Do not edit.",
        )
        .export(&types, specta_serde::PhasesFormat)
}
