// ABOUTME: TypeScript for the mirror frame contract, rendered from the Rust types
// by specta behind the `typescript-bindings` feature and committed as AppState.ts.
//
//   Frame + 19 section views ──specta::Type──▶ Types ──serde rules──▶ 64-bit as number ──▶ AppState.ts
//
// The export applies `specta_serde::PhasesFormat`, so every `rename`, `skip`,
// `skip_serializing_if` and custom `Serialize` in the redaction layer shapes the
// TypeScript the same way it shapes the JSON. A type whose serialized and
// deserialized shapes differ (a field a frame omits, a persisted type read back
// from disk) exports as a `*_Serialize` / `*_Deserialize` pair; frames are the
// `_Serialize` side. Every `serialize_with` field carries an explicit
// `specta(type)`: specta-serde refuses to guess a custom serializer's output.
//
// 64-bit integers: serde_json writes them as JSON numbers, so the honest
// TypeScript type is `number`. Every one on a frame is a count, an index, a
// version or an epoch-millisecond timestamp, far below 2^53, which is where a
// JSON number stops being exact.

use crate::wire::frame::{DaemonRead, Frame, FrameBatch, HostId, OversizeSection, Subscription};
use specta::Types;
use specta::datatype::{DataType, Fields, NamedReferenceType, Primitive, Reference};
use std::borrow::Cow;

/// Where the committed file lives, relative to the `ainb-app` crate.
pub const APP_STATE_TS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/bindings/AppState.ts");

/// Every type a mirror host sends, registered from its roots.
#[must_use]
pub fn types() -> Types {
    let types = Types::default()
        .register::<Frame>()
        .register::<FrameBatch>()
        .register::<HostId>()
        .register::<DaemonRead>()
        .register::<Subscription>()
        .register::<OversizeSection>();
    crate::wire::register_section_views(types)
}

/// The rendered `AppState.ts`.
///
/// # Errors
///
/// When a type in the closure cannot be expressed in TypeScript, or when a
/// serde attribute conflicts with its specta shape.
pub fn typescript() -> Result<String, BindingsError> {
    let both = specta_typescript::Typescript::default()
        .header(
            "// Generated by `cargo test -p ainb-app --features typescript-bindings --test bindings`\n\
             // from the Rust types behind ainb_app::wire (D15 mirror frames). Do not edit.",
        )
        .export(&types(), WireFormat)
        .map_err(BindingsError::Export)?;
    serialize_side(&both)
}

/// Why `AppState.ts` could not be rendered.
#[derive(Debug)]
pub enum BindingsError {
    /// specta could not express a type in the closure.
    Export(specta_typescript::Error),
    /// A serialize-side declaration still names a deserialize-side type.
    MixedPhases(String),
}

impl std::fmt::Display for BindingsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Export(error) => write!(f, "TypeScript export failed: {error}"),
            Self::MixedPhases(name) => {
                write!(f, "a serialize-side declaration references {name}")
            }
        }
    }
}

impl std::error::Error for BindingsError {}

/// Keep only what a frame can carry: the `_Serialize` side of every split type.
///
/// `PhasesFormat` emits both directions for any type whose serde shapes differ.
/// Nothing deserialises a frame's section types on the host, and the
/// deserialize side of a redacted type still names the fields the frame
/// withholds (`edit_buffer` where the frame sends `edit_len`), so it is dropped
/// and each `X = X_Serialize | X_Deserialize` alias becomes `X = X_Serialize`.
fn serialize_side(both: &str) -> Result<String, BindingsError> {
    let mut kept = Vec::new();
    for block in both.split("\n\n") {
        let name = block
            .lines()
            .find_map(|line| line.strip_prefix("export type "))
            .and_then(|rest| rest.split(|c: char| !(c.is_alphanumeric() || c == '_')).next())
            .unwrap_or_default();
        if name.ends_with("_Deserialize") {
            continue;
        }
        kept.push(block.replace(&format!(" | {name}_Deserialize"), ""));
    }
    let out = kept.join("\n\n");
    match out
        .split(|c: char| !(c.is_alphanumeric() || c == '_'))
        .find(|word| word.ends_with("_Deserialize"))
    {
        Some(name) => Err(BindingsError::MixedPhases(name.to_string())),
        None => Ok(out),
    }
}

/// serde's rules for both directions, then 64-bit integers as `number`.
struct WireFormat;

impl specta::Format for WireFormat {
    fn map_types(&'_ self, types: &Types) -> Result<Cow<'_, Types>, specta::FormatError> {
        let serde = specta_serde::PhasesFormat.map_types(types)?.into_owned();
        Ok(Cow::Owned(serde.map(|mut named| {
            if let Some(ty) = named.ty.as_mut() {
                narrow_wide_integers(ty);
            }
            named
        })))
    }

    fn map_type(
        &'_ self,
        types: &Types,
        dt: &DataType,
    ) -> Result<Cow<'_, DataType>, specta::FormatError> {
        let mut dt = specta_serde::PhasesFormat.map_type(types, dt)?.into_owned();
        narrow_wide_integers(&mut dt);
        Ok(Cow::Owned(dt))
    }
}

/// Rewrite every 64-bit and pointer-width integer to its 32-bit twin, which
/// specta-typescript renders as `number`, the type serde_json actually writes.
fn narrow_wide_integers(dt: &mut DataType) {
    match dt {
        DataType::Primitive(primitive) => {
            let narrowed = match primitive {
                Primitive::i64 | Primitive::isize | Primitive::i128 => Some(Primitive::i32),
                Primitive::u64 | Primitive::usize | Primitive::u128 => Some(Primitive::u32),
                _ => None,
            };
            if let Some(narrowed) = narrowed {
                *primitive = narrowed;
            }
        }
        DataType::List(list) => narrow_wide_integers(&mut list.ty),
        DataType::Map(map) => {
            narrow_wide_integers(map.key_ty_mut());
            narrow_wide_integers(map.value_ty_mut());
        }
        DataType::Struct(strukt) => narrow_fields(&mut strukt.fields),
        DataType::Enum(enumm) => {
            for (_, variant) in &mut enumm.variants {
                narrow_fields(&mut variant.fields);
            }
        }
        DataType::Tuple(tuple) => tuple.elements.iter_mut().for_each(narrow_wide_integers),
        DataType::Nullable(inner) => narrow_wide_integers(inner),
        DataType::Intersection(parts) => parts.iter_mut().for_each(narrow_wide_integers),
        DataType::Reference(Reference::Named(named)) => match &mut named.inner {
            NamedReferenceType::Inline { dt, .. } => narrow_wide_integers(dt),
            NamedReferenceType::Reference { generics, .. } => {
                for (_, generic) in generics {
                    narrow_wide_integers(generic);
                }
            }
            NamedReferenceType::Recursive(_) => {}
        },
        DataType::Reference(Reference::Opaque(_)) | DataType::Generic(_) => {}
    }
}

fn narrow_fields(fields: &mut Fields) {
    match fields {
        Fields::Unit => {}
        Fields::Unnamed(unnamed) => {
            for field in &mut unnamed.fields {
                if let Some(ty) = field.ty.as_mut() {
                    narrow_wide_integers(ty);
                }
            }
        }
        Fields::Named(named) => {
            for (_, field) in &mut named.fields {
                if let Some(ty) = field.ty.as_mut() {
                    narrow_wide_integers(ty);
                }
            }
        }
    }
}
